### ISSUE TITLE
Dynamic sized gui

### ISSUE THREAD

**Issue by DisabledMallis** [LoryTheRock24/McUItils#1]
One issue I notice with the library is the inability to set the amount of slots to a specific number. This isn't an action supported directly in bukkit, which is where the GuiLines enum comes in. This is a good idea on paper, but in execution this is just no suitable for some cases.

Heres my code using the lib to define the GUI:
```McGUI gui = new McGUI("Models", GuiLines.SIX_LINES, Engine.getInstance());```
looks fine, but i only need to use 5 slots, so in my opinion
```McGUI gui = new McGUI("Models", 5, Engine.getInstance());```
is much easier to write. Plus this would provide an ability to have dynamically sized GUIs.

How this can be done:
Replace the GuiLines enum parameter in the constructor with an integer. The amount of lines the gui should have can be determined with this algorithm i just came up with. You may be able to optimize it some more.
```(int)((slotCount / 9) + ((slotCount % 9) >= 1 ? 1 : 0))```

**Comment by LoRy24** [comment]
Ok, I think that I did it with the new commit. Thanks for the idea!
